name: Example workflow for S3 Deploy
on: [push]
jobs:
    run:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy
              uses: reggionick/s3-deploy@v3
              with:
                  folder: web
                  bucket: ${{ secrets.S3_BUCKET }}
                  bucket-region: ${{ secrets.S3_BUCKET_REGION }}
